version: 2.1

#orbs:
#  elixir: circleci/elixir@x.y # Replace x.y with the latest version of the Elixir orb
#  node: circleci/node@x.y    # Replace x.y with the latest version of the Node orb

workflows:
  version: 2
  ci:
    jobs:
      - mix_test_1_11_4
      - mix_test_1_12_3
      - npm_test
      - integration-test-elixir

jobs:
  mix_test_1_11_4:
    docker:
      - image: cimg/elixir:1.11.4
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-1.11.4-{{ checksum "mix.lock" }}
      - run: mix local.hex --force     
      - run: mix local.rebar --force
      - run: mix deps.get --only test
      - run: mix clean
      - run: mix test
      - save_cache:
          key: deps-1.11.4-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
  mix_test_1_12_3:
    docker:
      - image: cimg/elixir:1.12.3
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-1.12.3-{{ checksum "mix.lock" }}
      - run: mix local.hex --force      
      - run: mix local.rebar --force
      - run: mix deps.get --only test
      - run: mix clean
      - run: mix test
      - save_cache:
          key: deps-1.12.3-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
  npm_test:
    docker:
      - image: cimg/node:12.22.12 
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-npm-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install and test
          command: |
            cd assets
            npm install
            npm test
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  integration-test-elixir:
    docker:
      - image: cimg/base:current-20.04
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Download and install earthly
          command: sudo wget https://github.com/earthly/earthly/releases/download/v0.5.16/earthly-linux-amd64 -O /usr/local/bin/earthly && sudo chmod +x /usr/local/bin/earthly
      - run:
          name: Execute integration tests
          command: earthly -P --build-arg ELIXIR=1.14.0 --build-arg OTP=24.3.4 +integration-test
